function Hd = ChannelBasebandFilter
%TMP Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 11-Nov-2023 16:58:13

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in kHz.
Fs = (6.4e3/2)/208;  % Sampling Frequency

N    = 1030;     % Order
Fc   = .5;   % Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 6.2;      % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);


% [EOF]
